"""
Sidewinder AST Transformer for Python 3.12

This module transforms Python code for symbolic execution by:
1. Injecting __sidewinder_state parameter into all function definitions
2. Injecting __sidewinder_state argument into all function calls
3. Desugaring all syntactic sugar to explicit method calls
4. Converting all operations to __sidewinder_* methods
"""

import ast
from typing import Dict, List, Any, Union, overload

from sidewinder.analysis.transform.errors import SidewinderIllegalStateError
from sidewinder.analysis.transform.transformer_assign import SidewinderAssignTransformerMixin
from sidewinder.analysis.transform.transformer_base import SidewinderTransformerBase, T
from sidewinder.analysis.transform.transformer_classes import SidewinderClassTransformerMixin
from sidewinder.analysis.transform.transformer_context import TransformerContext
from sidewinder.analysis.transform.transformer_control_flow_breaker import SidewinderControlFlowBreakerTransformerMixin
from sidewinder.analysis.transform.transformer_expr import SidewinderExprTransformerMixin
from sidewinder.analysis.transform.transformer_for import SidewinderForTransformerMixin
from sidewinder.analysis.transform.transformer_functions import SidewinderFunctionTransformerMixin
from sidewinder.analysis.transform.transformer_helpers import SidewinderTransformerHelpers
from sidewinder.analysis.transform.transformer_if import SidewinderIfTransformerMixin
from sidewinder.analysis.transform.transformer_modules import SidewinderModuleTransformerMixin
from sidewinder.analysis.transform.transformer_try import SidewinderTryTransformerMixin
from sidewinder.analysis.transform.transformer_while import SidewinderWhileTransformerMixin
from sidewinder.analysis.transform.transformer_with import SidewinderWithTransformerMixin
from sidewinder.analysis.symbolic.hook import SidewinderHookNames


# This is not the transformer which is behind LLMs. This is an AST transformer, which transforms the abstract syntax trees generated by parsing
# source code into a different program.
# This transformer reduces all operations into a function call and assignments.
class SidewinderTransformer(
        SidewinderExprTransformerMixin,
        SidewinderWithTransformerMixin,
        SidewinderTryTransformerMixin,
        SidewinderForTransformerMixin,
        SidewinderWhileTransformerMixin,
        SidewinderIfTransformerMixin,
        SidewinderControlFlowBreakerTransformerMixin, 
        SidewinderAssignTransformerMixin,
        SidewinderClassTransformerMixin,
        SidewinderFunctionTransformerMixin, 
        SidewinderModuleTransformerMixin, 
        SidewinderTransformerHelpers, 
        SidewinderTransformerBase
    ):
    """
    Transforms Python AST for Sidewinder symbolic execution.
    
    Key transformations:
    - Thread SidewinderState through all functions
    - Desugar operators to __sidewinder_* method calls
    - Expand for loops to explicit iterator protocol
    - Convert comprehensions to explicit loops
    - Desugar with statements to __enter__/__exit__
    """
    def generic_visit(self, node: ast.AST) -> None:
        raise NotImplementedError("All visitor methods must be implemented and not delegated to generic_visit of ast.NodeTransformer")

    def __init__(self):
        # Track which functions have **kwargs in their signature
        self.function_signatures: Dict[str, bool] = {}  # name -> has_kwargs
        
        # Counter for generating fresh temporary variable names
        self.temp_counter = 0
        
        # Track current scope for variable naming
        self.current_scope = []

        # Current node where we append extra computation required
        self.current_context = TransformerContext()
            
    
    def visit_Delete(self, node: ast.Delete) -> Any:
        """Transform del statement."""
        new_targets = []
        for target in node.targets:
            if isinstance(target, ast.Name):
                # Case 1: del variable_name
                # Just a name binding removal - keep as is
                new_targets.append(target)
            else:
                raise NotImplementedError("TBI")
                # TODO: Should del x become x.__sidewinder_del__(__sidewinder_state)?
            
        node.targets = new_targets
        return node
    
    
    def visit_Assert(self, node: ast.Assert) -> list[ast.stmt]:
        """
        Transform assert statement to explicit sidewinder call.
        
        assert expr
        becomes:
        __sidewinder_assert__(expr<transformed>, __sidewinder_state=__sidewinder_state)
        
        assert expr, msg
        becomes:
        __sidewinder_assert__(expr<transformed>, msg<transformed>, __sidewinder_state=__sidewinder_state)
        """
        lowered_test = self._visit_expr(node.test)
        args = [lowered_test.expr]
        if node.msg is not None:
            lowered_msg = self._visit_expr(node.msg)
            args.append(lowered_msg.expr)

        ret: list[ast.stmt] = []
        ret.extend(lowered_test.stmts)
        ret.extend(lowered_msg.stmts)
        ret.append(ast.Expr(
            self._emit_hook_call(SidewinderHookNames.SIDEWINDER_ASSERT, *args),
            lineno=0, col_offset=0,
        ))
        return ret
    
    def visit_Import(self, node: ast.Import) -> Any:
        """Import statements pass through unchanged."""
        return node
    
    def visit_ImportFrom(self, node: ast.ImportFrom) -> Any:
        """From-import statements pass through unchanged."""
        return node
    
    def visit_Global(self, node: ast.Global) -> Any:
        """Global statements pass through unchanged."""
        return node
    
    def visit_Nonlocal(self, node: ast.Nonlocal) -> Any:
        """Nonlocal statements pass through unchanged."""
        return node
    
    def visit_Expr(self, node: ast.Expr) -> list[ast.stmt]:
        """
        Transform expression statement — a bare expression used as a statement.
        e.g. function calls whose return value is discarded: foo(), obj.method()
        """
        lowered_value = self._visit_expr(node.value)
        ret = []
        ret.extend(lowered_value.stmts)
        ret.append(ast.Expr(value=lowered_value.expr))
        return ret
    
    def visit_Pass(self, node: ast.Pass) -> Any:
        """Pass statements are unchanged."""
        return node
    
    
    def visit_Match(self, node: ast.Match) -> Any:
        """Transform match statement."""
        raise NotImplementedError("Match statements are not supported yet.")
    
    def visit_TypeAlias(self, node: ast.TypeAlias) -> Any:
        """Transform type alias statement."""
        raise NotImplementedError("Type alias statements are not supported yet")
    
    # ========== Pattern Matching Nodes ==========
    
    def visit_match_case(self, node: ast.match_case) -> Any:
        """Transform match case."""
        raise NotImplementedError("Match statements are not supported yet.")
    
    def visit_MatchValue(self, node: ast.MatchValue) -> Any:
        """Transform match value pattern."""
        raise NotImplementedError("Match statements are not supported yet.")
    
    def visit_MatchSingleton(self, node: ast.MatchSingleton) -> Any:
        """Match singleton pattern is unchanged."""
        raise NotImplementedError("Match statements are not supported yet.")
    
    def visit_MatchSequence(self, node: ast.MatchSequence) -> Any:
        """Transform match sequence pattern."""
        raise NotImplementedError("Match statements are not supported yet.")
    
    def visit_MatchMapping(self, node: ast.MatchMapping) -> Any:
        """Transform match mapping pattern."""
        raise NotImplementedError("Match statements are not supported yet.")
    
    def visit_MatchClass(self, node: ast.MatchClass) -> Any:
        """Transform match class pattern."""
        raise NotImplementedError("Match statements are not supported yet.")
    
    def visit_MatchStar(self, node: ast.MatchStar) -> Any:
        """Match star pattern is unchanged."""
        raise NotImplementedError("Match statements are not supported yet.")
    
    def visit_MatchAs(self, node: ast.MatchAs) -> Any:
        """Transform match as pattern."""
        raise NotImplementedError("Match statements are not supported yet.")
    
    def visit_MatchOr(self, node: ast.MatchOr) -> Any:
        """Transform match or pattern."""
        raise NotImplementedError("Match statements are not supported yet.")
    
    # ========== Type Parameter Nodes ==========
    
    def visit_TypeVar(self, node: ast.TypeVar) -> Any:
        """Transform type variable."""
        raise NotImplementedError("TypeVar nodes are not supported yet")
    
    def visit_ParamSpec(self, node: ast.ParamSpec) -> Any:
        """Transform parameter specification."""
        raise NotImplementedError("ParamSpec nodes are not supported yet")
    
    def visit_TypeVarTuple(self, node: ast.TypeVarTuple) -> Any:
        """Transform type variable tuple."""
        raise NotImplementedError("TypeVar nodes are not supported yet")
    
    # ========== Helper/Supporting Nodes ==========
    
    def visit_comprehension(self, node: ast.comprehension) -> Any:
        """Transform comprehension clause."""
        raise SidewinderIllegalStateError("Did not expect to visit comprehension node")
    
    def visit_arguments(self, node: ast.arguments) -> Any:
        """Transform function arguments."""
        # Arguments are handled by FunctionDef/Lambda visitors
        return node
    
    def visit_arg(self, node: ast.arg) -> list[ast.AST]:
        """Transform function argument."""
        # TODO: This is not a expr or stmt, if theres a complex expression here it may :blows raspberry:. (Pydantic annotations could complain)
        if node.annotation:
            lowered_annotation = self._visit_expr(node.annotation)
            node.annotation = lowered_annotation.expr
            ret = []
            ret.extend(lowered_annotation.stmts)
            ret.append(node)
            return ret
        else:
            return [node]
    
    def visit_keyword(self, node: ast.keyword) -> list[ast.stmt]:
        """Transform keyword argument."""
        lowered_keyword = self._visit_expr(node.value)
        node.value = lowered_keyword.expr
        ret = []
        ret.extend(lowered_keyword.stmts)
        ret.append(node)
        return ret
    
    def visit_alias(self, node: ast.alias) -> Any:
        """Import alias is unchanged."""
        return node
    
    def visit_withitem(self, node: ast.withitem) -> Any:
        """Transform with item."""
        raise SidewinderIllegalStateError("Did not expect to visit withitem node")

def transform_code(source_code: str) -> str:
    """
    Transform Python source code for Sidewinder symbolic execution.
    
    Args:
        source_code: Python source code as string
        
    Returns:
        Transformed Python source code as string
    """
    tree = ast.parse(source_code)
    transformer = SidewinderTransformer()
    transformed_tree = transformer.visit(tree)
    ast.fix_missing_locations(transformed_tree)
    return ast.unparse(transformed_tree)


if __name__ == "__main__":
    # Test the transformer
#     test_code = """
# def add(x, y):
#     return x + y

# def greet(name, **kwargs):
#     print(f"Hello {name}")

# result = add(1, 2)

# for i in range(10):
#     print(i)

    test_code = """
if x:
    y = 1
else:
    y = 2
"""

# a = [x * 2 for x in range(5)]
# """
    
    print("=== Original Code ===")
    print(test_code)
    print("\n=== Transformed Code ===")
    transformed_code = transform_code(test_code)
    print(transformed_code)
    # exec(transformed_code)

       
